# Generated by Django 6.0.7 on 2026-08-02 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0007_remove_organization_slug'),
        ('talents', '0008_talentprofile_availability_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='organizations.organization')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_organizations', to='talents.talentprofile')),
            ],
            options={
                'unique_together': {('talent', 'organization')},
            },
        ),
    ]
