# Generated by Django 6.0.7 on 2026-08-02 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_organizationfollow'),
        ('organizations', '0008_organization_cover_photo_organization_followers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationfollow',
            options={},
        ),
        migrations.AlterField(
            model_name='organizationfollow',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_followers', to='organizations.organization'),
        ),
    ]
