# Generated by Django 6.0.7 on 2026-08-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventfeedback_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('APPROVED', 'Approved'), ('ATTENDED', 'Attended'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='REGISTERED', max_length=20),
        ),
    ]
