# Generated by Django 6.0.7 on 2026-08-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventregistration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('APPROVED', 'Approved'), ('ATTENDED', 'Attended'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='REGISTERED', max_length=20),
        ),
    ]
