# Generated by Django 6.0.7 on 2026-08-05 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventregistration_status'),
        ('talents', '0009_talentprofile_followers_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='attendance_marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='attendance_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('APPROVED', 'Approved'), ('ATTENDED', 'Attended'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('ATTENDED', 'Attended')], db_index=True, default='REGISTERED', max_length=20),
        ),
        migrations.CreateModel(
            name='EventCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Certificate of Participation', max_length=200)),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='events.event')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_certificates', to='talents.talentprofile')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
