# Generated by Django 6.0.7 on 2026-08-05 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventregistration_attendance_marked_and_more'),
        ('organizations', '0008_organization_cover_photo_organization_followers'),
        ('talents', '0009_talentprofile_followers_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventcertificate',
            old_name='certificate_number',
            new_name='certificate_code',
        ),
        migrations.RenameField(
            model_name='eventcertificate',
            old_name='title',
            new_name='certificate_title',
        ),
        migrations.AlterUniqueTogether(
            name='eventcertificate',
            unique_together={('event', 'talent')},
        ),
        migrations.AlterField(
            model_name='eventcertificate',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_certificates', to='organizations.organization'),
        ),
        migrations.RemoveField(
            model_name='eventcertificate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='eventcertificate',
            name='verified',
        ),
    ]
