# Generated by Django 6.0.7 on 2026-08-09 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_certificate_number_eventcertificate_certificate_code_and_more'),
        ('organizations', '0008_organization_cover_photo_organization_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='events/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='events.event')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_media', to='organizations.organization')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
