# Generated by Django 6.0.7 on 2026-08-14 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_eventregistration_status'),
        ('organizations', '0008_organization_cover_photo_organization_followers'),
        ('talents', '0009_talentprofile_followers_count_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventregistration',
            name='unique_event_user',
        ),
        migrations.AlterUniqueTogether(
            name='eventcertificate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='eventcertificate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventcertificate',
            name='verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='talents.talentprofile'),
        ),
        migrations.AddConstraint(
            model_name='eventcertificate',
            constraint=models.UniqueConstraint(fields=('event', 'talent'), name='unique_event_certificate'),
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='user',
        ),
    ]
