# Generated by Django 6.0.7 on 2026-08-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('opportunities', '0004_opportunity_experience_level_opportunity_skills_and_more'),
        ('talents', '0009_talentprofile_followers_count_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('talent', 'opportunity'), name='unique_talent_opportunity_application'),
        ),
    ]
