# Generated by Django 6.0.7 on 2026-08-30 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_remove_sport_image_sport_created_at_sport_icon_and_more'),
        ('talents', '0010_talentprofile_talent_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsTalentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talent_profiles', to='sports.sport')),
                ('sport_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talent_profiles', to='sports.sportcategory')),
                ('talent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sports_profile', to='talents.talentprofile')),
            ],
        ),
    ]
