# Generated by Django 6.0.7 on 2026-07-25 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0002_remove_sport_image_sport_created_at_sport_icon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('league', models.CharField(blank=True, max_length=200)),
                ('level', models.CharField(choices=[('PROFESSIONAL', 'Professional'), ('SEMI_PRO', 'Semi Professional'), ('AMATEUR', 'Amateur'), ('ACADEMY', 'Academy'), ('SCHOOL', 'School')], default='AMATEUR', max_length=20)),
                ('founded', models.PositiveIntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clubs/logos/')),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sport')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='club_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TalentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.PositiveIntegerField()),
                ('max_age', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sportcategory')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='core.club')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sport')),
            ],
        ),
    ]
