# Generated by Django 6.0.7 on 2026-07-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentrequirement',
            name='club',
        ),
        migrations.RemoveField(
            model_name='talentrequirement',
            name='category',
        ),
        migrations.RemoveField(
            model_name='talentrequirement',
            name='sport',
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='TalentRequirement',
        ),
    ]
