# Generated by Django 6.0.2 on 2026-07-30 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0004_opportunity_experience_level_opportunity_skills_and_more'),
        ('organizations', '0001_initial'),
        ('talents', '0008_talentprofile_availability_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('SHORTLISTED', 'Shortlisted'), ('INVITED', 'Invited'), ('INTERVIEW', 'Interview'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected')], default='SHORTLISTED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_pipeline', to='opportunities.opportunity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_stages', to='organizations.organization')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_stages', to='talents.talentprofile')),
            ],
        ),
    ]
