# Generated by Django 6.0.2 on 2026-08-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_opportunity_experience_level_opportunity_skills_and_more'),
        ('organizations', '0008_organization_cover_photo_organization_followers'),
        ('recruitment', '0001_initial'),
        ('talents', '0009_talentprofile_followers_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruitmentstage',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddConstraint(
            model_name='recruitmentstage',
            constraint=models.UniqueConstraint(fields=('organization', 'talent', 'opportunity'), name='unique_recruitment_candidate'),
        ),
    ]
