# Generated by Django 6.0.7 on 2026-07-26 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0004_athletemedia_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('performance_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('achievement_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('experience_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('verification_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='talent_score', to='athletes.athleteprofile')),
            ],
        ),
    ]
