# Generated by Django 6.0.7 on 2026-07-29 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('organizations', '0001_initial'),
        ('talents', '0007_talentprofile_experience_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views', to='organizations.organization')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views', to='talents.talentprofile')),
            ],
        ),
    ]
