# Generated by Django 6.0.7 on 2026-07-29 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_talentprofileview'),
        ('opportunities', '0004_opportunity_experience_level_opportunity_skills_and_more'),
        ('organizations', '0001_initial'),
        ('talents', '0007_talentprofile_experience_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_history', to='opportunities.opportunity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_history', to='organizations.organization')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_history', to='talents.talentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
