# Generated by Django 6.0.7 on 2026-08-01 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='organization',
            name='organization_type',
        ),
        migrations.AddField(
            model_name='sportsorganizationprofile',
            name='headquarters',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sportsorganizationprofile',
            name='stadium',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sportsorganizationprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='organizations.organizationcategory'),
        ),
        migrations.CreateModel(
            name='OrganizationDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='organizations.organizationcategory')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='organizations.organizationdomain'),
        ),
        migrations.DeleteModel(
            name='OrganizationType',
        ),
    ]
