# Generated by Django 6.0.7 on 2026-08-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_organization_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationdomain',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='organizationdomain',
            unique_together={('category', 'name')},
        ),
    ]
