# Generated by Django 6.0.7 on 2026-08-02 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_organizationdomain_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='organizationdomain',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterModelOptions(
            name='sportsorganizationprofile',
            options={'ordering': ['organization__name']},
        ),
        migrations.RemoveField(
            model_name='sportsorganizationprofile',
            name='headquarters',
        ),
        migrations.AddField(
            model_name='organization',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='headquarters',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='organization',
            name='level',
            field=models.CharField(choices=[('GLOBAL', 'Global'), ('CONTINENTAL', 'Continental'), ('NATIONAL', 'National'), ('REGIONAL', 'Regional'), ('LOCAL', 'Local')], default='LOCAL', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='official',
            field=models.BooleanField(default=True, help_text='Official organization seeded or verified by Awinlink.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_size',
            field=models.CharField(blank=True, choices=[('SMALL', '1-50 Employees'), ('MEDIUM', '51-250 Employees'), ('LARGE', '251-1000 Employees'), ('ENTERPRISE', '1000+ Employees')], max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MERGED', 'Merged'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='sportsorganizationprofile',
            name='colors',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='sportsorganizationprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sportsorganizationprofile',
            name='level',
            field=models.CharField(choices=[('PROFESSIONAL', 'Professional'), ('SEMI_PRO', 'Semi Professional'), ('AMATEUR', 'Amateur'), ('ACADEMY', 'Academy'), ('SCHOOL', 'School'), ('NATIONAL_TEAM', 'National Team'), ('FEDERATION', 'Federation'), ('LEAGUE', 'League')], default='AMATEUR', max_length=30),
        ),
    ]
