# Generated by Django 6.0.7 on 2026-08-02 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organization_options_and_more'),
    ]

    operations = [

    ]
