# Generated by Django 6.0.7 on 2026-08-02 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_remove_organization_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='organizations/covers/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_organizations', to=settings.AUTH_USER_MODEL),
        ),
    ]
