# Generated by Django 6.0.7 on 2026-10-03 15:04

import cloudinary.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
        ('organizations', '0008_organization_cover_photo_organization_followers'),
        ('skills', '0003_skillrelationship'),
        ('sports', '0003_sportstalentprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending review'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('billing_model', models.CharField(choices=[('CPM', 'Cost per thousand impressions'), ('CPC', 'Cost per click')], default='CPM', max_length=3)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('daily_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_per_thousand_impressions', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('cost_per_click', models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=10)),
                ('target_categories', models.JSONField(blank=True, default=list)),
                ('frequency_cap', models.PositiveSmallIntegerField(default=3, help_text='Maximum impressions per user in the selected frequency window.')),
                ('frequency_window_hours', models.PositiveSmallIntegerField(default=24)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domains', models.ManyToManyField(blank=True, related_name='advertising_campaigns', to='domains.talentdomain')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertising_campaigns', to='organizations.organization')),
                ('skills', models.ManyToManyField(blank=True, related_name='advertising_campaigns', to='skills.skill')),
                ('sports', models.ManyToManyField(blank=True, related_name='advertising_campaigns', to='sports.sport')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(blank=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('video', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, resource_type='video', verbose_name='video')),
                ('cta_label', models.CharField(default='Learn more', max_length=40)),
                ('destination_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement', to='advertising.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Successful'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=10)),
                ('authorization_url', models.URLField(blank=True, max_length=500)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='advertising.campaign')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AdvertisementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('IMPRESSION', 'Impression'), ('CLICK', 'Click'), ('VIDEO_VIEW', 'Video view')], db_index=True, max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='advertising.advertisement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisement_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['advertisement', 'user', 'event_type', 'created_at'], name='ad_event_frequency_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(('total_budget__gt', 0)), name='advertising_campaign_budget_positive'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='advertising_campaign_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(('frequency_cap__gt', 0), ('frequency_window_hours__gt', 0)), name='advertising_campaign_frequency_positive'),
        ),
    ]
