# Generated by Django 6.0.7 on 2026-10-03 15:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
        ('domains', '0001_initial'),
        ('organizations', '0008_organization_cover_photo_organization_followers'),
        ('skills', '0003_skillrelationship'),
        ('sports', '0003_sportstalentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='destination_url',
            field=models.URLField(max_length=500, validators=[django.core.validators.URLValidator(schemes=('https',))]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='cost_per_click',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='cost_per_thousand_impressions',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='frequency_cap',
            field=models.PositiveSmallIntegerField(default=3, help_text='Maximum impressions per user in the selected frequency window.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='frequency_window_hours',
            field=models.PositiveSmallIntegerField(default=24, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(('cost_per_thousand_impressions__gt', 0), ('cost_per_click__gt', 0)), name='advertising_campaign_rates_positive'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(('daily_budget__isnull', True), models.Q(('daily_budget__gt', 0), ('daily_budget__lte', models.F('total_budget'))), _connector='OR'), name='advertising_campaign_daily_budget_valid'),
        ),
        migrations.AddConstraint(
            model_name='campaignpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='advertising_payment_amount_positive'),
        ),
    ]
