# Generated by Django 6.0.7 on 2026-10-03 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_alter_advertisement_destination_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementevent',
            name='tracking_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='advertisementevent',
            constraint=models.UniqueConstraint(condition=models.Q(('tracking_id', ''), _negated=True), fields=('advertisement', 'user', 'event_type', 'tracking_id'), name='advertising_event_tracking_unique'),
        ),
    ]
