# Generated by Django 6.0.2 on 2026-07-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ATHLETE', 'Athlete'), ('ORGANIZATION', 'Organization'), ('SCOUT', 'Scout'), ('COACH', 'Coach'), ('ADMIN', 'Admin')], default='ATHLETE', max_length=20),
        ),
    ]
