# Generated by Django 6.0.7 on 2026-09-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization_username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
