# Generated by Django 6.0.7 on 2026-08-22 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0008_organization_cover_photo_organization_followers'),
        ('talents', '0009_talentprofile_followers_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('biography', models.TextField(blank=True)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scouts', to='organizations.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scout_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScoutTalentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('scout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_views', to='scouts.scoutprofile')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scout_views', to='talents.talentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ScoutTalentBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_talents', to='scouts.scoutprofile')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scout_bookmarks', to='talents.talentprofile')),
            ],
            options={
                'unique_together': {('scout', 'talent')},
            },
        ),
        migrations.CreateModel(
            name='ScoutTalentFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_talents', to='scouts.scoutprofile')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scout_followers', to='talents.talentprofile')),
            ],
            options={
                'unique_together': {('scout', 'talent')},
            },
        ),
    ]
