# Generated by Django 6.0.7 on 2026-07-27 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        ('opportunities', '0003_opportunity_deadline_opportunity_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='opportunities.opportunity'),
        ),
    ]
