# Generated by Django 6.0.7 on 2026-07-29 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_conversation_opportunity'),
        ('opportunities', '0004_opportunity_experience_level_opportunity_skills_and_more'),
        ('organizations', '0001_initial'),
        ('talents', '0007_talentprofile_experience_level_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('talent', 'organization', 'opportunity')},
        ),
    ]
