# Generated by Django 6.0.7 on 2026-09-05 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_existing_calls(apps, schema_editor):
    Call = apps.get_model("messaging", "Call")
    CallParticipant = apps.get_model("messaging", "CallParticipant")

    for call in Call.objects.all():

        # Preserve the original caller as the initiator
        if call.caller_id:
            call.initiated_by_id = call.caller_id
            call.save(update_fields=["initiated_by"])

            CallParticipant.objects.get_or_create(
                call_id=call.id,
                user_id=call.caller_id,
                defaults={
                    "status": "JOINED",
                    "joined_at": call.answered_at or call.started_at,
                }
            )

        # Preserve the original receiver
        if call.receiver_id:
            participant_status = (
                "JOINED"
                if call.status in ["ACCEPTED", "ENDED"]
                else "RINGING"
            )

            CallParticipant.objects.get_or_create(
                call_id=call.id,
                user_id=call.receiver_id,
                defaults={
                    "status": participant_status,
                    "joined_at": call.answered_at,
                }
            )


class Migration(migrations.Migration):

    dependencies = [
        (
            "messaging",
            "0009_conversation_created_by_conversation_image_and_more"
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        # ---------------------------------------------------------
        # 1. Add the new initiator field while old caller/receiver
        #    fields still exist.
        # ---------------------------------------------------------

        migrations.AddField(
            model_name="call",
            name="initiated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="initiated_calls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),

        # ---------------------------------------------------------
        # 2. Create the participant table.
        # ---------------------------------------------------------

        migrations.CreateModel(
            name="CallParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INVITED", "Invited"),
                            ("RINGING", "Ringing"),
                            ("JOINED", "Joined"),
                            ("REJECTED", "Rejected"),
                            ("LEFT", "Left"),
                            ("MISSED", "Missed"),
                        ],
                        default="INVITED",
                        max_length=10,
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        blank=True,
                        null=True
                    ),
                ),
                (
                    "left_at",
                    models.DateTimeField(
                        blank=True,
                        null=True
                    ),
                ),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="messaging.call",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("call", "user"),
                        name="unique_call_participant",
                    ),
                ],
            },
        ),

        # ---------------------------------------------------------
        # 3. Copy existing caller/receiver data into the new
        #    structure BEFORE removing the old fields.
        # ---------------------------------------------------------

        migrations.RunPython(
            migrate_existing_calls,
            migrations.RunPython.noop,
        ),

        # ---------------------------------------------------------
        # 4. Update call status choices.
        # ---------------------------------------------------------

        migrations.AlterField(
            model_name="call",
            name="status",
            field=models.CharField(
                choices=[
                    ("RINGING", "Ringing"),
                    ("ACTIVE", "Active"),
                    ("ENDED", "Ended"),
                    ("MISSED", "Missed"),
                ],
                default="RINGING",
                max_length=10,
            ),
        ),

        # ---------------------------------------------------------
        # 5. Only now remove the old one-to-one fields.
        # ---------------------------------------------------------

        migrations.RemoveField(
            model_name="call",
            name="caller",
        ),

        migrations.RemoveField(
            model_name="call",
            name="receiver",
        ),
    ]