# Generated by Django 6.0.7 on 2026-08-21 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
        ('talents', '0009_talentprofile_followers_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachTalentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_views', to='coaches.coachprofile')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_views', to='talents.talentprofile')),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='CoachTalentFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_talents', to='coaches.coachprofile')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coached_by', to='talents.talentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('coach', 'talent'), name='unique_coach_talent_follow')],
            },
        ),
    ]
