# Generated by Django 6.0.7 on 2026-08-21 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0002_coachtalentview_coachtalentfollow'),
        ('talents', '0009_talentprofile_followers_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachTalentBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Private notes about this talent.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_talents', to='coaches.coachprofile')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_coaches', to='talents.talentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('coach', 'talent'), name='unique_coach_talent_bookmark')],
            },
        ),
    ]
