# Generated by Django 6.0.7 on 2026-09-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0003_coachtalentbookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='coach_category',
            field=models.CharField(blank=True, choices=[('SPORTS', 'Sports'), ('SCIENCE_TECHNOLOGY', 'Science & Technology'), ('ARTS', 'Arts'), ('OTHERS', 'Others')], max_length=30, null=True),
        ),
    ]
