# Generated by Django 6.0.7 on 2026-08-02 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_post_location_post_visibility_savedpost'),
        ('organizations', '0007_remove_organization_slug'),
        ('talents', '0008_talentprofile_availability_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='post',
            name='talent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='talents.talentprofile'),
        ),
    ]
