# Generated by Django 6.0.7 on 2026-07-26 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('biography', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='talents/profile/')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='talents/cover/')),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domains', models.ManyToManyField(blank=True, to='domains.talentdomain')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='talent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
