# Generated by Django 6.0.7 on 2026-07-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('talents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='skills.skill'),
        ),
    ]
