# Generated by Django 6.0.7 on 2026-07-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0006_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='experience_level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('EXPERT', 'Expert')], default='BEGINNER', max_length=20),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='preferred_work_type',
            field=models.CharField(choices=[('REMOTE', 'Remote'), ('ONSITE', 'On Site'), ('HYBRID', 'Hybrid')], default='REMOTE', max_length=20),
        ),
    ]
