# Generated by Django 6.0.2 on 2026-07-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0007_talentprofile_experience_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='availability_status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Currently Busy'), ('NOT_LOOKING', 'Not Looking')], default='AVAILABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='profile_visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('ORGANIZATIONS', 'Organizations Only'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=20),
        ),
    ]
