# Generated by Django 6.0.7 on 2026-08-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0008_talentprofile_availability_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='followers_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='is_role_model',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='role_model_category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
