# Generated by Django 6.0.7 on 2026-08-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0009_talentprofile_followers_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='talent_category',
            field=models.CharField(blank=True, choices=[('SPORTS', 'Sports'), ('SCIENCE_TECHNOLOGY', 'Science & Technology'), ('ARTS', 'Arts'), ('OTHERS', 'Others')], max_length=30, null=True),
        ),
    ]
