# Generated by Django 6.0.2 on 2026-09-17 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0010_talentprofile_talent_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleModelAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20)),
                ('score', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_model_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_model_assignments', to='talents.talentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
