# Generated by Django 6.0.2 on 2026-09-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0012_rolemodelassignment_reviewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemodelassignment',
            name='assignment_type',
            field=models.CharField(choices=[('QUALIFIED', 'Qualification Based'), ('MANUAL', 'Manual Assignment')], default='QUALIFIED', max_length=20),
        ),
    ]
