# Generated by Django 6.0.2 on 2026-09-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0013_rolemodelassignment_assignment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='talent_area',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
