# Generated by Django 6.0.7 on 2026-07-29 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('talents', '0007_talentprofile_experience_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_talents', to='organizations.organization')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_by', to='talents.talentprofile')),
            ],
            options={
                'unique_together': {('organization', 'talent')},
            },
        ),
    ]
