# Generated by Django 6.0.7 on 2026-07-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortlist',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='shortlist',
            name='notes',
            field=models.TextField(blank=True, help_text='Private notes about this talent.'),
        ),
        migrations.AddField(
            model_name='shortlist',
            name='starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shortlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
