# Generated by Django 6.0.7 on 2026-07-26 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='opportunity_type',
            field=models.CharField(choices=[('JOB', 'Job'), ('TRIAL', 'Sports Trial'), ('SCHOLARSHIP', 'Scholarship'), ('AUDITION', 'Audition'), ('COMPETITION', 'Competition')], default='JOB', max_length=20),
        ),
        migrations.CreateModel(
            name='OpportunityRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.PositiveIntegerField(default=1, help_text='1 = low importance, 5 = very important')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='opportunities.opportunity')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skill')),
            ],
        ),
    ]
