# Generated by Django 6.0.7 on 2026-07-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_opportunity_deadline_opportunity_location_and_more'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='experience_level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('EXPERT', 'Expert')], default='BEGINNER', max_length=20),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='skills',
            field=models.ManyToManyField(blank=True, to='skills.skill'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='work_type',
            field=models.CharField(choices=[('REMOTE', 'Remote'), ('ONSITE', 'On Site'), ('HYBRID', 'Hybrid')], default='REMOTE', max_length=20),
        ),
    ]
