# Generated by Django 6.0.2 on 2026-08-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_remove_course_published_course_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
