# Generated by Django 6.0.2 on 2026-08-18 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_course_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='learning.enrollment'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
