# Generated by Django 6.0.7 on 2026-07-26 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talents', '0002_talentprofile_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document'), ('PROJECT', 'Project'), ('CERTIFICATE', 'Certificate'), ('ACHIEVEMENT', 'Achievement')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='portfolio/files/')),
                ('link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='talents.talentprofile')),
            ],
        ),
    ]
