# Generated by Django 6.0.7 on 2026-07-27 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
        ('opportunities', '0003_opportunity_deadline_opportunity_location_and_more'),
        ('organizations', '0001_initial'),
        ('talents', '0003_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_invitations', to='opportunities.opportunity'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='talents.talentprofile'),
        ),
    ]
