# Generated by Django 6.0.7 on 2026-08-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_alter_invitation_opportunity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
