# Generated by Django 6.0.7 on 2026-07-25 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('preferred_foot', models.CharField(blank=True, choices=[('LEFT', 'Left'), ('RIGHT', 'Right'), ('BOTH', 'Both')], max_length=10, null=True)),
                ('biography', models.TextField(blank=True)),
                ('current_team', models.CharField(blank=True, max_length=200)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='athletes/profile_photos/')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='athletes/cover_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
