# Generated by Django 6.0.7 on 2026-07-25 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athleteprofile',
            name='position',
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.sportcategory'),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.sport'),
        ),
    ]
