# Generated by Django 6.0.7 on 2026-07-25 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_remove_athleteprofile_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athleteprofile',
            name='preferred_foot',
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='experience_level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('AMATEUR', 'Amateur'), ('PROFESSIONAL', 'Professional'), ('ELITE', 'Elite')], default='AMATEUR', max_length=20),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='athletes/cover/'),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='height',
            field=models.DecimalField(decimal_places=2, help_text='Height in centimeters', max_digits=5),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='athletes/profile/'),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Weight in kilograms', max_digits=5),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('year', models.IntegerField()),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='athletes.athleteprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AthleteMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('VIDEO', 'Video'), ('IMAGE', 'Image')], max_length=10)),
                ('file', models.FileField(upload_to='athletes/media/')),
                ('title', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='athletes.athleteprofile')),
            ],
        ),
    ]
