# Generated by Django 6.0.7 on 2026-07-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_remove_athleteprofile_preferred_foot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletemedia',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='athletemedia',
            name='media_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], max_length=10),
        ),
    ]
