# Generated by Django 6.0.7 on 2026-09-11 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skillcategory_name_alter_skill_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('related_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='skills.skill')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_skills', to='skills.skill')),
            ],
            options={
                'unique_together': {('skill', 'related_skill')},
            },
        ),
    ]
