# Generated by Django 6.0.7 on 2026-08-30 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talents', '0010_talentprofile_talent_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherTalentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('field', models.CharField(blank=True, max_length=200)),
                ('experience_description', models.TextField(blank=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('skills_description', models.TextField(blank=True)),
                ('projects_description', models.TextField(blank=True)),
                ('achievements_description', models.TextField(blank=True)),
                ('interests', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('other_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('talent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='other_profile', to='talents.talentprofile')),
            ],
        ),
    ]
