# Generated by Django 6.0.2 on 2026-07-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('INVITATION', 'Invitation'), ('APPLICATION', 'Application'), ('MESSAGE', 'Message'), ('SYSTEM', 'System'), ('PROFILE_SAVED', 'Profile Saved'), ('INVITATION_DECLINED', 'Invitation Declined')], default='SYSTEM', max_length=30),
        ),
    ]
