# Generated by Django 6.0.7 on 2026-08-02 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_alter_comment_options'),
        ('notifications', '0002_alter_notification_notification_type'),
        ('opportunities', '0004_opportunity_experience_level_opportunity_skills_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opportunities.opportunity'),
        ),
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.post'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LIKE', 'Post Like'), ('COMMENT', 'Post Comment'), ('FOLLOW', 'New Follow'), ('INVITATION', 'Invitation'), ('APPLICATION', 'Application'), ('MESSAGE', 'Message'), ('SHORTLIST', 'Shortlisted'), ('AI_MATCH', 'AI Recommendation'), ('SYSTEM', 'System')], default='SYSTEM', max_length=30),
        ),
    ]
