# Generated by Django 6.0.7 on 2026-08-09 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_alter_conversation_options_conversation_updated_at_and_more'),
        ('notifications', '0003_alter_notification_options_notification_opportunity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='messaging.conversation'),
        ),
    ]
