# Generated by Django 6.0.2 on 2026-08-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LIKE', 'Post Like'), ('COMMENT', 'Post Comment'), ('FOLLOW', 'New Follow'), ('INVITATION', 'Invitation'), ('APPLICATION', 'Application'), ('MESSAGE', 'Message'), ('SHORTLIST', 'Shortlisted'), ('AI_MATCH', 'AI Recommendation'), ('SYSTEM', 'System'), ('SHARE', 'Share')], default='SYSTEM', max_length=30),
        ),
    ]
