# Generated by Django 6.0.2 on 2026-09-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LIKE', 'Post Like'), ('COMMENT', 'Post Comment'), ('FOLLOW', 'New Follow'), ('INVITATION', 'Invitation'), ('APPLICATION', 'Application'), ('MESSAGE', 'Message'), ('SHORTLIST', 'Shortlisted'), ('AI_MATCH', 'AI Recommendation'), ('SYSTEM', 'System'), ('SHARE', 'Share'), ('CONNECTION', 'Connection'), ('INCOMING_CALL', 'Incoming Call'), ('MISSED_CALL', 'Missed Call')], default='SYSTEM', max_length=30),
        ),
    ]
